channelId:
  - '1116760172090642436'
token: 
  - MTExMjgwMzIwMjM3NTYxNDQ3NA.G1boK0.FxEG1rS0gjn_Vy-deOwbvSsKb_SnZStXwBprAA
  - MTExMTk5NzkyOTc3MTc3ODA5OA.GIOpbz.lddyGFNEb_-s0YhMLmOled5127zGEUq92sG0mw
interval: 60000
